/**
 * Read-only CoordinationHost dashboard projection and self-contained page.
 *
 * The host's authoritative snapshots deliberately contain more information
 * than a browser needs (device ids on holders, lock ids, intent descriptions,
 * and agent ids). This module projects only the narrow coordination metadata
 * that is useful to a team dashboard. It never reads host state itself, so the
 * projection is deterministic and directly unit-testable.
 */

import type {
  RiskLevel,
  SessionId,
  SessionStateSnapshot,
} from "@cfls/protocol";

/** One session snapshot plus the devices currently connected to that session. */
export interface DashboardSessionInput {
  session: SessionId;
  snapshot: SessionStateSnapshot;
  connectedDevices: readonly string[];
}

/** Input supplied by the HTTP server to the pure dashboard projection. */
export interface DashboardInput {
  /** Current host uptime, supplied by the server to keep this function pure. */
  uptimeSeconds: number;
  /** ISO timestamp generated by the server when it builds the response. */
  generatedAt: string;
  sessions: readonly DashboardSessionInput[];
}

/** A lock safe to display in the dashboard. */
export interface DashboardLock {
  path: string;
  holder: string;
  mode: RiskLevel;
  eventRevision: number;
}

/** A member actively editing a repository-relative path. */
export interface DashboardPresence {
  member: string;
  path: string;
}

/** A member's declared plan to create a repository-relative path. */
export interface DashboardPlannedCreation {
  member: string;
  path: string;
}

/** Dashboard data for one repository session. */
export interface DashboardSession {
  repoId: string;
  teamId: string;
  branch: string;
  highestRevision: number;
  connectedDevices: string[];
  locks: DashboardLock[];
  presence: DashboardPresence[];
  plannedCreations: DashboardPlannedCreation[];
}

/** The serializable payload returned from `/api/coordination`. */
export interface DashboardState {
  uptimeSeconds: number;
  generatedAt: string;
  totals: {
    sessions: number;
    devices: number;
    locks: number;
  };
  sessions: DashboardSession[];
}

function compareStrings(left: string, right: string): number {
  return left.localeCompare(right);
}

function uniqueSorted(values: readonly string[]): string[] {
  return [...new Set(values)].sort(compareStrings);
}

/**
 * Build the small, serializable metadata view consumed by the web dashboard.
 *
 * Only winning locks are shown: a concurrent claim is useful to the protocol,
 * but it is not the lock currently held for that scope. Stopped presence is
 * similarly historical state rather than active editing. No source content,
 * credentials, holder device ids, lock ids, intent descriptions, or agent ids
 * are copied into the result.
 */
export function buildDashboardState(input: DashboardInput): DashboardState {
  const sessions = input.sessions
    .map(({ session, snapshot, connectedDevices }): DashboardSession => {
      const locks = snapshot.locks
        .filter((lock) => !lock.concurrent)
        .map(
          (lock): DashboardLock => ({
            path: lock.scope,
            holder: lock.holder.memberId,
            mode: lock.mode,
            eventRevision: lock.eventRevision,
          }),
        )
        .sort(
          (left, right) =>
            compareStrings(left.path, right.path) ||
            compareStrings(left.holder, right.holder) ||
            compareStrings(left.mode, right.mode) ||
            left.eventRevision - right.eventRevision,
        );

      const presence = snapshot.presence
        .filter((entry) => entry.state !== "stopped")
        .map(
          (entry): DashboardPresence => ({
            member: entry.member.memberId,
            path: entry.path,
          }),
        )
        .sort(
          (left, right) =>
            compareStrings(left.path, right.path) ||
            compareStrings(left.member, right.member),
        );

      const plannedCreations = snapshot.intents
        .flatMap((intent) =>
          intent.createPaths.map(
            (creation): DashboardPlannedCreation => ({
              member: intent.owner.memberId,
              path: creation.path,
            }),
          ),
        )
        .sort(
          (left, right) =>
            compareStrings(left.path, right.path) ||
            compareStrings(left.member, right.member),
        );

      return {
        repoId: session.repoId,
        teamId: session.teamId,
        branch: session.branch,
        highestRevision: snapshot.highestRevision,
        connectedDevices: uniqueSorted(connectedDevices),
        locks,
        presence,
        plannedCreations,
      };
    })
    .sort(
      (left, right) =>
        compareStrings(left.repoId, right.repoId) ||
        compareStrings(left.branch, right.branch) ||
        compareStrings(left.teamId, right.teamId),
    );

  const devices = new Set<string>();
  let locks = 0;
  for (const session of sessions) {
    for (const device of session.connectedDevices) {
      devices.add(device);
    }
    locks += session.locks.length;
  }

  return {
    uptimeSeconds: input.uptimeSeconds,
    generatedAt: input.generatedAt,
    totals: {
      sessions: sessions.length,
      devices: devices.size,
      locks,
    },
    sessions,
  };
}

const HTML_ESCAPES: Readonly<Record<string, string>> = {
  "&": "&amp;",
  "<": "&lt;",
  ">": "&gt;",
  '"': "&quot;",
  "'": "&#39;",
};

/**
 * Escape a dynamic value before it is inserted into HTML. The inline client
 * uses the same escape map, and this exported helper keeps that guarantee
 * directly unit-testable without a browser runtime.
 */
export function escapeDashboardHtml(value: unknown): string {
  return String(value).replace(
    /[&<>"']/g,
    (character) => HTML_ESCAPES[character] ?? character,
  );
}

/**
 * Render the standalone live dashboard. All data is fetched client-side from
 * `/api/coordination`; no host state is interpolated into this document.
 */
export function renderDashboardHtml(): string {
  const escapeMap = JSON.stringify(HTML_ESCAPES);

  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="color-scheme" content="dark">
    <title>CFLS Coordination Dashboard</title>
    <style>
      :root {
        color-scheme: dark;
        --canvas: #09111f;
        --surface: #101b2e;
        --surface-strong: #15243c;
        --line: #273a57;
        --muted: #93a8c7;
        --text: #edf5ff;
        --blue: #69b9ff;
        --cyan: #46dbc6;
        --green: #58dc91;
        --amber: #f3bb5c;
        --red: #fb7f8d;
        --shadow: 0 18px 55px rgba(0, 0, 0, .26);
      }

      * { box-sizing: border-box; }
      html { background: var(--canvas); }
      body {
        min-width: 320px;
        margin: 0;
        color: var(--text);
        background:
          radial-gradient(circle at 10% -10%, rgba(57, 119, 218, .27), transparent 36rem),
          radial-gradient(circle at 95% 5%, rgba(34, 183, 165, .12), transparent 32rem),
          var(--canvas);
        font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      }
      code, .mono { font-family: "SFMono-Regular", Consolas, "Liberation Mono", monospace; }
      .shell { width: min(1440px, calc(100% - 2rem)); margin: 0 auto; }
      .topbar {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 1rem;
        padding: 1.2rem 0 1rem;
        border-bottom: 1px solid rgba(147, 168, 199, .16);
      }
      .brand { display: flex; align-items: center; gap: .78rem; min-width: 0; }
      .brand-mark {
        display: grid;
        width: 2.25rem;
        height: 2.25rem;
        place-items: center;
        border: 1px solid rgba(105, 185, 255, .5);
        border-radius: .72rem;
        color: var(--blue);
        background: linear-gradient(140deg, rgba(105, 185, 255, .19), rgba(70, 219, 198, .10));
        box-shadow: inset 0 1px 0 rgba(255, 255, 255, .08);
        font-weight: 800;
      }
      .brand-title { margin: 0; font-size: 1rem; letter-spacing: .01em; }
      .brand-subtitle { margin: .12rem 0 0; color: var(--muted); font-size: .8rem; }
      .connection {
        display: inline-flex;
        align-items: center;
        gap: .48rem;
        flex: 0 0 auto;
        color: var(--muted);
        font-size: .85rem;
      }
      .status-dot, .device-dot {
        display: inline-block;
        width: .58rem;
        height: .58rem;
        border-radius: 50%;
        background: var(--green);
        box-shadow: 0 0 0 4px rgba(88, 220, 145, .12);
      }
      .connection.is-reconnecting .status-dot { background: var(--amber); box-shadow: 0 0 0 4px rgba(243, 187, 92, .12); }
      main { padding: 1.5rem 0 3rem; }
      .intro { display: flex; justify-content: space-between; gap: 1rem; align-items: end; margin-bottom: 1.25rem; }
      .eyebrow { margin: 0 0 .35rem; color: var(--cyan); font-size: .72rem; font-weight: 750; letter-spacing: .12em; text-transform: uppercase; }
      h1 { margin: 0; font-size: clamp(1.65rem, 3vw, 2.45rem); letter-spacing: -.035em; }
      .last-updated { margin: 0; color: var(--muted); font-size: .84rem; text-align: right; }
      .totals { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: .8rem; margin-bottom: 1.4rem; }
      .metric, .session-card, .empty-state {
        border: 1px solid var(--line);
        background: linear-gradient(145deg, rgba(21, 36, 60, .96), rgba(16, 27, 46, .92));
        box-shadow: var(--shadow);
      }
      .metric { border-radius: 1rem; padding: 1rem 1.1rem; }
      .metric-label { display: block; color: var(--muted); font-size: .78rem; font-weight: 650; letter-spacing: .04em; text-transform: uppercase; }
      .metric-value { display: block; margin-top: .28rem; color: var(--text); font-size: 1.7rem; font-weight: 760; letter-spacing: -.04em; }
      .sessions { display: grid; gap: 1rem; }
      .session-card { overflow: hidden; border-radius: 1rem; }
      .session-head {
        display: flex;
        justify-content: space-between;
        gap: 1rem;
        align-items: start;
        padding: 1.05rem 1.15rem;
        border-bottom: 1px solid var(--line);
        background: rgba(8, 17, 31, .24);
      }
      .repo { min-width: 0; margin: 0; font-size: 1rem; }
      .repo code { overflow-wrap: anywhere; color: #dbeeff; font-size: .93rem; }
      .session-meta { display: flex; flex-wrap: wrap; gap: .45rem; margin: .5rem 0 0; color: var(--muted); font-size: .82rem; }
      .tag { padding: .2rem .48rem; border: 1px solid rgba(147, 168, 199, .25); border-radius: 99px; background: rgba(147, 168, 199, .08); }
      .revision { flex: 0 0 auto; color: var(--muted); font-size: .82rem; text-align: right; }
      .revision strong { display: block; margin-top: .12rem; color: var(--blue); font-size: 1.02rem; }
      .devices { display: flex; flex-wrap: wrap; align-items: center; gap: .45rem; padding: .8rem 1.15rem; border-bottom: 1px solid var(--line); }
      .devices-label { color: var(--muted); font-size: .78rem; font-weight: 650; }
      .device { display: inline-flex; max-width: 100%; align-items: center; gap: .38rem; padding: .28rem .5rem; border: 1px solid rgba(88, 220, 145, .22); border-radius: .48rem; background: rgba(88, 220, 145, .07); font-size: .76rem; }
      .device code { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
      .device-dot { width: .42rem; height: .42rem; box-shadow: none; }
      .no-devices { color: var(--muted); font-size: .82rem; }
      .session-grid { display: grid; grid-template-columns: 1.38fr 1fr 1fr; gap: 0; }
      .panel { min-width: 0; padding: 1rem 1.15rem 1.2rem; }
      .panel + .panel { border-left: 1px solid var(--line); }
      .panel h3 { margin: 0 0 .8rem; font-size: .86rem; letter-spacing: -.01em; }
      .table-wrap { overflow-x: auto; }
      table { width: 100%; border-collapse: collapse; font-size: .8rem; }
      th { padding: 0 0 .48rem; color: var(--muted); font-size: .67rem; font-weight: 700; letter-spacing: .07em; text-align: left; text-transform: uppercase; }
      td { padding: .55rem .38rem .55rem 0; border-top: 1px solid rgba(147, 168, 199, .13); vertical-align: middle; }
      td code { color: #dbeeff; overflow-wrap: anywhere; }
      .mode { display: inline-flex; padding: .18rem .4rem; border-radius: .35rem; font-size: .69rem; font-weight: 720; white-space: nowrap; }
      .mode-soft { color: #a9c8f2; background: rgba(105, 185, 255, .14); }
      .mode-coordinate { color: #ffdd9b; background: rgba(243, 187, 92, .15); }
      .mode-hard { color: #ffadb6; background: rgba(251, 127, 141, .15); }
      .activity-list { display: grid; gap: .55rem; margin: 0; padding: 0; list-style: none; }
      .activity-item { display: grid; gap: .12rem; padding: .58rem .64rem; border: 1px solid rgba(147, 168, 199, .14); border-radius: .58rem; background: rgba(9, 17, 31, .28); }
      .activity-member { color: #e7f2ff; font-size: .79rem; font-weight: 670; }
      .activity-path { color: var(--muted); font-size: .74rem; overflow-wrap: anywhere; }
      .empty-copy { margin: 0; color: var(--muted); font-size: .83rem; line-height: 1.55; }
      .empty-state { padding: 2.4rem 1.25rem; border-radius: 1rem; text-align: center; }
      .empty-state h2 { margin: 0 0 .5rem; font-size: 1.1rem; }
      .empty-state p { max-width: 38rem; margin: 0 auto; color: var(--muted); line-height: 1.55; }
      @media (max-width: 980px) {
        .session-grid { grid-template-columns: 1fr 1fr; }
        .panel:nth-child(3) { grid-column: 1 / -1; border-top: 1px solid var(--line); border-left: 0; }
      }
      @media (max-width: 650px) {
        .shell { width: min(100% - 1rem, 1440px); }
        .topbar, .intro, .session-head { align-items: start; flex-direction: column; }
        .last-updated, .revision { text-align: left; }
        .totals, .session-grid { grid-template-columns: 1fr; }
        .panel + .panel, .panel:nth-child(3) { border-top: 1px solid var(--line); border-left: 0; }
      }
    </style>
  </head>
  <body>
    <div class="shell">
      <header class="topbar">
        <div class="brand">
          <div class="brand-mark" aria-hidden="true">&#8596;</div>
          <div>
            <p class="brand-title">CFLS Coordination Dashboard</p>
            <p class="brand-subtitle">Read-only, metadata-only team awareness</p>
          </div>
        </div>
        <div id="connection" class="connection" aria-live="polite">
          <span class="status-dot" aria-hidden="true"></span>
          <span id="connection-text">Connecting...</span>
        </div>
      </header>
      <main>
        <div class="intro">
          <div>
            <p class="eyebrow">Live coordination state</p>
            <h1>See the work already in motion.</h1>
          </div>
          <p id="last-updated" class="last-updated">Waiting for host data...</p>
        </div>
        <section id="totals" class="totals" aria-label="Coordination totals"></section>
        <section id="sessions" class="sessions" aria-live="polite" aria-busy="true"></section>
      </main>
    </div>
    <script>
      (() => {
        const HTML_ESCAPES = ${escapeMap};
        const totalsElement = document.getElementById("totals");
        const sessionsElement = document.getElementById("sessions");
        const connectionElement = document.getElementById("connection");
        const connectionTextElement = document.getElementById("connection-text");
        const lastUpdatedElement = document.getElementById("last-updated");

        function escapeHtml(value) {
          return String(value).replace(/[&<>"']/g, (character) => HTML_ESCAPES[character] || character);
        }

        function arrayOf(value) {
          return Array.isArray(value) ? value : [];
        }

        function safeNumber(value, fallback) {
          const number = Number(value);
          return Number.isFinite(number) ? number : fallback;
        }

        function displayValue(value) {
          return value === undefined || value === null || value === "" ? "-" : String(value);
        }

        function formatTime(value) {
          const date = new Date(String(value));
          return Number.isNaN(date.getTime()) ? displayValue(value) : date.toLocaleString();
        }

        function modeClass(mode) {
          if (mode === "hard") return "mode-hard";
          if (mode === "coordination-required") return "mode-coordinate";
          return "mode-soft";
        }

        function renderDevices(devices) {
          const items = arrayOf(devices);
          if (items.length === 0) {
            return '<span class="no-devices">No devices connected</span>';
          }
          return items.map((device) =>
            '<span class="device"><span class="device-dot" aria-hidden="true"></span><code>' +
            escapeHtml(displayValue(device)) +
            '</code></span>',
          ).join("");
        }

        function renderLocks(locks) {
          const items = arrayOf(locks);
          if (items.length === 0) {
            return '<p class="empty-copy">No locks held</p>';
          }
          return '<div class="table-wrap"><table><thead><tr><th scope="col">Path</th><th scope="col">Holder</th><th scope="col">Mode</th><th scope="col">Rev.</th></tr></thead><tbody>' +
            items.map((lock) =>
              '<tr><td><code>' + escapeHtml(displayValue(lock && lock.path)) + '</code></td>' +
              '<td>' + escapeHtml(displayValue(lock && lock.holder)) + '</td>' +
              '<td><span class="mode ' + modeClass(lock && lock.mode) + '">' + escapeHtml(displayValue(lock && lock.mode)) + '</span></td>' +
              '<td class="mono">' + escapeHtml(displayValue(lock && lock.eventRevision)) + '</td></tr>',
            ).join("") +
            '</tbody></table></div>';
        }

        function renderActivity(items, emptyText) {
          const values = arrayOf(items);
          if (values.length === 0) {
            return '<p class="empty-copy">' + escapeHtml(emptyText) + '</p>';
          }
          return '<ul class="activity-list">' + values.map((item) =>
            '<li class="activity-item"><span class="activity-member">' + escapeHtml(displayValue(item && item.member)) +
            '</span><code class="activity-path">' + escapeHtml(displayValue(item && item.path)) + '</code></li>',
          ).join("") + '</ul>';
        }

        function renderSession(session) {
          const locks = arrayOf(session && session.locks);
          const presence = arrayOf(session && session.presence);
          const creations = arrayOf(session && session.plannedCreations);
          return '<article class="session-card">' +
            '<header class="session-head"><div><h2 class="repo"><code>' + escapeHtml(displayValue(session && session.repoId)) +
            '</code></h2><div class="session-meta"><span class="tag">team ' + escapeHtml(displayValue(session && session.teamId)) +
            '</span><span class="tag">branch ' + escapeHtml(displayValue(session && session.branch)) +
            '</span></div></div><div class="revision">Highest revision<strong class="mono">' +
            escapeHtml(displayValue(session && session.highestRevision)) + '</strong></div></header>' +
            '<div class="devices"><span class="devices-label">Connected devices</span>' + renderDevices(session && session.connectedDevices) + '</div>' +
            '<div class="session-grid"><section class="panel"><h3>Active locks <span class="mono">(' + safeNumber(locks.length, 0) +
            ')</span></h3>' + renderLocks(locks) + '</section><section class="panel"><h3>Editing now <span class="mono">(' + safeNumber(presence.length, 0) +
            ')</span></h3>' + renderActivity(presence, "Nobody is actively editing") + '</section><section class="panel"><h3>Planned creations <span class="mono">(' + safeNumber(creations.length, 0) +
            ')</span></h3>' + renderActivity(creations, "No planned file creations") + '</section></div></article>';
        }

        function render(state) {
          const sessions = arrayOf(state && state.sessions);
          const totals = state && typeof state.totals === "object" && state.totals !== null ? state.totals : {};
          totalsElement.innerHTML =
            '<article class="metric"><span class="metric-label">Sessions</span><strong class="metric-value">' +
            safeNumber(totals.sessions, sessions.length) + '</strong></article>' +
            '<article class="metric"><span class="metric-label">Devices online</span><strong class="metric-value">' +
            safeNumber(totals.devices, 0) + '</strong></article>' +
            '<article class="metric"><span class="metric-label">Active locks</span><strong class="metric-value">' +
            safeNumber(totals.locks, 0) + '</strong></article>';
          lastUpdatedElement.textContent = "Last updated " + formatTime(state && state.generatedAt) +
            " | host uptime " + safeNumber(state && state.uptimeSeconds, 0) + "s";
          if (sessions.length === 0) {
            sessionsElement.innerHTML = '<article class="empty-state"><h2>No active sessions</h2><p>When a team member connects to a repository session, its coordination metadata will appear here.</p></article>';
          } else {
            sessionsElement.innerHTML = sessions.map(renderSession).join("");
          }
          sessionsElement.setAttribute("aria-busy", "false");
        }

        function setConnection(status, reconnecting) {
          connectionTextElement.textContent = status;
          connectionElement.classList.toggle("is-reconnecting", reconnecting);
        }

        async function refresh() {
          try {
            const response = await fetch("/api/coordination", { cache: "no-store" });
            if (!response.ok) throw new Error("Dashboard API returned " + response.status);
            render(await response.json());
            setConnection("Live - refreshes every 2 seconds", false);
          } catch {
            sessionsElement.setAttribute("aria-busy", "false");
            setConnection("Reconnecting...", true);
          }
        }

        void refresh();
        window.setInterval(() => { void refresh(); }, 2000);
      })();
    </script>
  </body>
</html>`;
}
